import Image from "next/image"
import Link from "next/link"
import { ArrowRight, CalendarDays, Clock3, MapPin, Stethoscope } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { doctors, disclaimer, type BlogPost } from "@/lib/blog-data"

export function BlogHero({ detail = false }: { detail?: boolean }) {
  return <section className="bg-primary text-primary-foreground"><div className="container max-w-7xl px-4 py-16 md:px-8 md:py-24"><p className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.2em] text-primary-foreground/70"><Stethoscope className="size-4" /> Amma Eye Care Journal</p><h1 className="max-w-4xl text-balance text-4xl font-bold tracking-tight md:text-6xl">{detail ? "Cataract Surgery at Amma Eye Care Hospitals, Hyderabad" : "Clear answers for healthier vision"}</h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-8 text-primary-foreground/80">{detail ? "A patient-friendly guide to cataract evaluation, treatment, surgery, and choosing an eye doctor in Hyderabad." : "Trusted guidance from the ophthalmology team at Amma Eye Care Hospitals."}</p></div></section>
}

export function BlogListing({ post }: { post: BlogPost }) {
  return <><BlogHero /><section className="container max-w-7xl px-4 py-14 md:px-8"><div className="mb-10"><Badge variant="secondary">Latest article</Badge><h2 className="mt-3 text-3xl font-bold tracking-tight">Eye care, explained simply</h2></div><Card className="overflow-hidden border-border/70 shadow-sm md:grid md:grid-cols-[1.05fr_1fr]"><div className="relative min-h-64 bg-muted md:min-h-full"><Image src={post.image} alt="Cataract surgery care at Amma Eye Care Hospitals" fill className="object-cover" /></div><CardContent className="flex flex-col justify-center gap-5 p-7 md:p-10"><div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground"><Badge variant="outline">{post.category}</Badge><span className="flex items-center gap-1"><CalendarDays className="size-4" /> {post.date}</span><span className="flex items-center gap-1"><Clock3 className="size-4" /> {post.readTime}</span></div><h3 className="text-2xl font-bold leading-tight md:text-3xl">{post.title}</h3><p className="leading-7 text-muted-foreground">{post.excerpt}</p><Button asChild className="w-fit"><Link href={`/blogs/${post.slug}`}>Read article <ArrowRight data-icon="inline-end" /></Link></Button></CardContent></Card></section></>
}

export function BlogDetail({ post }: { post: BlogPost }) {
  return <><BlogHero detail /><article className="container max-w-7xl px-4 py-12 md:px-8"><div className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="max-w-3xl"><div className="mb-8 flex flex-wrap items-center gap-4 text-sm text-muted-foreground"><Badge>{post.category}</Badge><span className="flex items-center gap-1"><CalendarDays className="size-4" /> {post.date}</span><span className="flex items-center gap-1"><Clock3 className="size-4" /> {post.readTime}</span></div><div className="relative mb-10 aspect-[16/8] overflow-hidden rounded-xl"><Image src={post.image} alt="Cataract surgery care" fill priority className="object-cover" /></div>{post.sections.map((section) => <section key={section.heading} className="mb-10"><h2 className="mb-4 text-2xl font-bold tracking-tight">{section.heading}</h2>{section.paragraphs?.map((p) => <p key={p} className="mb-4 leading-8 text-muted-foreground">{p}</p>)}{section.bullets && <ul className="grid gap-3 rounded-xl bg-muted/50 p-6 text-muted-foreground md:grid-cols-2">{section.bullets.map((item) => <li key={item} className="flex gap-2 leading-6"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" />{item}</li>)}</ul>}</section>)}<Card className="border-amber-200 bg-amber-50/60"><CardHeader><h2 className="text-lg font-bold">Medical disclaimer</h2></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{disclaimer}</p></CardContent></Card></div><aside className="flex flex-col gap-6"><Card><CardHeader><h2 className="text-xl font-bold">Meet our eye doctors</h2></CardHeader><CardContent className="flex flex-col gap-5">{doctors.map(([name, bio, image]) => <div key={name} className="flex gap-3"><Image src={image} alt={name} width={56} height={56} className="size-14 rounded-full object-cover" /><div><p className="font-semibold">{name}</p><p className="mt-1 text-sm leading-5 text-muted-foreground">{bio}</p></div></div>)}</CardContent></Card><Card className="bg-primary text-primary-foreground"><CardContent className="flex flex-col gap-4 p-6"><MapPin className="size-6" /><h2 className="text-xl font-bold">Ready to see clearly?</h2><p className="text-sm leading-6 text-primary-foreground/80">Book a cataract consultation at our Kokapet or LB Nagar hospital.</p><Button asChild variant="secondary"><Link href="/bookings">Book consultation</Link></Button></CardContent></Card></aside></div></article></>
}
