// Data layer for the insurance directory — kept separate from UI so the
// partner list can be updated (or swapped for a CMS/API call) without
// touching any presentation code.

export const INSURANCE_PARTNERS: string[] = [
  "ACKO General Insurance Company",
  "Aditya Birla Health Insurance Co. Ltd.",
  "AKNA Health Insurance TPA Pvt. Ltd.",
  "Anmol Medicare Insurance (TPA) Ltd.",
  "Bajaj General Insurance Ltd.",
  "Care Health Insurance Ltd",
  "Chola MS General Insurance",
  "DHFL General Insurance Ltd",
  "Digit Insurance",
  "East West Assist Insurance TPA Pvt. Ltd.",
  "Edelweiss General Insurance Co Ltd",
  "ERICSON INSURANCE TPA PVT LTD",
  "Family Health Plan Insurance TPA Limited (FHPL)",
  "Future Generali India Insurance Company",
  "Galaxy Health Ins Company Ltd",
  "Generali Central Insurance Company Limited",
  "Genins India Insurance TPA Ltd",
  "Good Health Insurance TPA (GHPL)",
  "HDFC ERGO General Insurance Company Limited.",
  "Health Insurance TPA of India Ltd (hitpa)",
  "HEALTHINDIA Insurance TPA Services Pvt. Ltd.",
  "Heritage Health Insurance TPA",
  "ICICI Lombard General Insurance Company Limited",
  "IFFCO TOKIO GENERAL INSURANCE",
  "L&T General Insurance",
  "Liberty General Insurance",
  "Link-K Insurance TPA Pvt Ltd",
  "Magma General Insurance Ltd",
  "ManipalCigna Health Insurance Company Ltd",
  "Max Bupa Health Insurance Company Ltd",
  "MDIndia Healthcare Services (TPA) Pvt. Ltd.",
  "Medi Assist Insurance TPA Pvt Ltd",
  "Medsave Health Insurance TPA Ltd",
  "Medvantage Insurance TPA PVT LTD",
  "National Insurance Company Limited",
  "NAVI GENERAL INSURANCE",
  "New India Assurance Company Limited",
  "Niva Bupa Health Insurance Company Limited",
  "Oriental Insurance Company Ltd.",
  "Paramount Health Services & Insurance TPA Pvt. Ltd.",
  "Park Mediclaim insurance TPA Pvt Ltd.",
  "Raheja QBE",
  "Raksha Health Insurance TPA",
  "RELIANCE GENERAL INS",
  "Religare Health Ins Comp. Ltd",
  "Royal Sundaram Gen. Ins",
  "Safeway Insurance TPA Pvt Ltd",
  "SBI General Insurance Company Limited",
  "Star Health and Allied Insurance Co Ltd",
  "TATA AIG GIC",
  "United India Insurance Company Limited",
  "UnitedHealth Care Parekh Insurance TPA (PVT) Ltd",
  "Universal Sompo General Insurance Co Ltd",
  "Vidal health insurance TPA",
  "Vipul Medcorp Insurance TPA Private Limited",
  "Volo Health Insurance TPA Pvt. Ltd.",
  "Zuno General Insurance Ltd",
  "Zurich Kotak General Insurance Company Limited",
]